name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore -c Release

    - name: Publish
      run: dotnet publish --no-build --no-restore -c Release -o out

    - name: Unit Test
      run: dotnet test --no-build --verbosity normal ./out/IntegreNet.Tests.dll

    - name: Upload artifacts
      uses: actions/upload-artifact@v2.2.4
      with:
        name: build
        path: out
        if-no-files-found: error

  integration:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - uses: actions/checkout@v2

      - name: Run test containers
        uses: isbang/compose-action@v1.0.0
        with:
          compose-file: ./.docker/docker-compose.yml

      - name: Download published artifacts
        uses: actions/download-artifact@v2
        with:
          name: build

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Integration Test
        run: dotnet test --no-build --verbosity normal ./IntegreNet.Tests.Integration.dll
